version: '3.8'

services:
  vision-cls:
    build:
      context: .
      dockerfile: Dockerfile
    image: vision-cls:latest
    container_name: vision-cls-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./notebooks:/app/notebooks
      - ./src:/app/src
    ports:
      - "8888:8888"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
